# Generated by Django 3.1.2 on 2021-11-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default=' ', verbose_name='Модель телефона')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('image', models.ImageField(default='C:\\Users\\Тимофей\\PycharmProjects\\Django\\dj-homeworks\\databases\\work_with_database\\телефон.png', upload_to='', verbose_name='Изображение')),
                ('release_date', models.DateField(default='1/1/2001', verbose_name='Дата выпуска')),
                ('lte_exists', models.BooleanField(default=False, verbose_name='Наличие LTE')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
            ],
        ),
    ]
